version: '3.8'
services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: meta
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: metacatalog
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data

  frontend:
    image: ghcr.io/hydrocode-de/metacatalog-ingest:latest
    link:
      - db
    ports:
      - 8000:8000
    environment:
      METACATALOG_URI: postgresql://meta:${POSTGRES_PASSWORD}@db:5432/metacatalog
      HOST: 0.0.0.0
      PORT: 8000
      
  # run a jupyter server for us locally
  jupyter:
    build:
      context: ./python-metacatalog
      dockerfile: Dockerfile
    link:
      - db
    ports:
      - 4242:4242
    environment:
      JUYPTER_TOKEN: ${JUPYTER_TOKEN}
      METACATALOG_URI: postgresql://meta:${POSTGRES_PASSWORD}@db:5432/metacatalog
    command: jupyter notebook --no-browser --IdentityProvider.token=${JUPYTER_TOKEN} --host=0.0.0.0 --port=4242
    volumes:
      ./data/notebooks:/data

