version: '3.8'
services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: meta
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: metacatalog
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data

  frontend:
    image: ghcr.io/hydrocode-de/metacatalog-ingest:latest
    ports:
      - 8000:8000
    environment:
      METACATALOG_URI: postgresql://meta:${POSTGRES_PASSWORD}@db:5432/metacatalog
      HOST: 0.0.0.0
      PORT: 8000


